# Generated by Django 3.2.4 on 2023-11-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterpdf',
            name='pdf_file',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
