# Generated by Django 3.2.4 on 2023-11-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_chapterpdf_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptervideo',
            name='video_file',
            field=models.URLField(),
        ),
    ]
